case: "Final_Cases"
working_dir: "~/hdd1/zhf/AI-driven_EM_Simulation/Codes" 
node: 100

passivity: True
verbose: True
trial: True
distributed: False
multilayers: True

config:
  dir: "../Configs/Parameters/Final_Cases_4_1115.json"

dataset_generation:
  dir: "../Data/Samples"
  mode: "initial"
  name: "Final_Cases_4_1115"
  complete: True
  batch_num: 200
  train_test_split: True
  train:
    sampling_num: 1500
    sampling_method: "uniform"
    random_state: "random"
  test:
    sampling_num: 1500
    sampling_method: "uniform"
    random_state: "random"

num_epochs: 10000
batch_size: 32

validation:
  valid_per_epoch: 100
  
ckpt:
  read: True
  save: True
  save_per_epoch: 100
  early_stop_thres: 7.0e-7

datasets:
  dir: "../Data/Dataset"
  mode: "final"
  datasets: ["Final_Cases_4_1115"]
  sampling_method: "guided"
  sampling_ratio: 0.05

fig:
  dir: "../Figures"
  plot_during_train: True
  plot_per_epoch: 1000
  example_num: 5

model:
  name: "mlp_srsi"
  trunk_layers: [2048, 2048, 2048]
  head_layers: [2048, 2048]
  
optimizer:
  name: "adamw"
  lr: 0.0001
  weight_decay: 0.0001

scheduler:
  name: "constant"

loss:
  name: "mse"